name: money_statistic
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_svg: 0.19.0
  table_calendar: 2.2.0
  firebase_core: ^0.4.4
  firebase_auth: ^0.16.1
  splashscreen: ^1.3.5
  flutter_bloc: ^0.5.0
  firebase_storage: ^3.1.3
  cloud_firestore: ^0.13.7
  persistent_bottom_nav_bar: ^3.0.0
  keyboard_avoider: ^0.1.2
  flutter_datetime_picker: ^1.5.0
  get: ^3.21.2
  toast: ^0.1.5
  modal_bottom_sheet: ^1.0.0
  image_picker: ^0.6.7+14
  flutter_launcher_icons: 0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/splash.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
